{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fasterize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fasterize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fasterize/fasterize_{{ version }}.tar.gz
  sha256: 231aa04f505ec08162edfc3f3a410205a2bfde6c3261415ef7258f1ddab2375f

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  ## NB: missing win r-raster (track https://github.com/conda-forge/r-raster-feedstock/issues/34)
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-codetools
    - r-rcpp
    - r-rcpparmadillo
    - r-raster >=2.8_3
    - r-wk
  run:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-raster >=2.8_3
    - r-wk

test:
  requires:
    - r-codetools
  commands:
    - $R -e "library('fasterize')"           # [not win]
    - "\"%R%\" -e \"library('fasterize')\""  # [win]

about:
  home: https://github.com/ecohealthalliance/fasterize
  license: MIT
  summary: Provides a drop-in replacement for rasterize() from the 'raster' package that takes polygon vector or data frame objects, and is much faster. There is support for the main options provided by the rasterize() function, including setting the field used and background value, and options for aggregating multi-layer
    rasters. Uses the scan line algorithm attributed to Wylie et al. (1967) <doi:10.1145/1465611.1465619>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
