{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fasterize
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fasterize_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fasterize/fasterize_{{ version }}.tar.gz
  sha256: d44f101aec29aee285c4c7b578e26d11b6add423336ace90a7c22e07cfc1c3b4

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-raster >=2.8_3
    - r-wk
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcpparmadillo
    - r-raster >=2.8_3
    - r-wk

test:
  commands:
    - $R -e "library('fasterize')"           # [not win]
    - "\"%R%\" -e \"library('fasterize')\""  # [win]

about:
  home: https://github.com/ecohealthalliance/fasterize
  license: MIT
  summary: Provides a drop-in replacement for rasterize() from the 'raster'
    package that takes polygon vector or data frame objects, and is much faster. 
    There is support for the main options provided by the rasterize() function, 
    including setting the field used and background value, and options for 
    aggregating multi-layer rasters. Uses the scan line algorithm attributed to
    Wylie et al. (1967) <doi:10.1145/1465611.1465619>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
