bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: bJ9hQIMO1KT5fEx+zQJRcH17+JbxaYS5ybhaYA68WC2BuxMwqf+c309cBIk1A03CruSVFCscuMuO6fmNclZ5wqVFBBjfXyOYOIb4f72AuZ0+DcKLDnhB0C+utRoBXuAHQ795FjEFyCDG2oBuXeTwDS34JaVmHghUzL0X7e2wQKfEk01FsW5Vbx+gqnbn3MJEMqH3V/teZRjiE+3hztIS2GM+tt3F4oFqyU9N/1hcg1Kt+nHIYhQd9pdqIjL5oWieeBE4/Z0Jf8sc3fKeNCdp3BfNS1pnIBTx3+/HWE1dQcB6/42p9IbWQivhHEp9YbZEZ5ml0S/n1AuU2ShpeMjJVPgpOMTmr79lYpuADw5yksX8uVYH1tHN8l1ohqRnc2vjaNO7IiUmAmmzAQmrVP/iZdqxT+dKdzA+Wmk5Pa1GzHyhc2WDsRe+lB+FC4MzsAWktGY//f5kygivcqygN2vVApzcmfb2kJVZQD7RxjYbSVVDtl6fjBc3qvOgZWl6Zc6jqYB5UWtPGpnr7V2/wmxOVLMK4RswhRVCW1pyjC3MOhjWNldpCfQn0Oua2z00pPjAdQ3TBAs6cSP1BMpFdxeHfjuGlQAXQ8UBGjJQPuNes4/YDekwL/qDY0IximPyC9tAa2tDsLyBVaMkcn/UMLvAULnkwhwzFYGZfWnNjAaV21A=
conda_forge_output_validation: true
